### ISSUE TITLE
Player Stance needs clarification

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#115]
- Does it apply to the legs only or also the arms?
  - My opinion: It includes the arms since they can be used to block other players. If the arms don't count, the entire rule could be removed.
- Does it apply during all game states? Especially during penalty kicks for the goalkeeper, which can't block any other players in that situation anyway.

**Comment by PatrickGoettsch** [comment]
What is the result of yesterday's discussion on this topic?

**Comment by ahasselbring** [comment]
We couldn't really agree on how the rule should be changed (I believe we agreed that extending the arms does count as a wide stance, but it was mentioned that a better definition of "significantly wider than the width of the robot's shoulders" was required and it we discussed if the rule should be changed such that a wide stance is only penalized when it leads to actual *obstruction* of another player, but it was noted that this could be too difficult to decide for referees) and I said I would elaborate a written suggestion and make a PR - which I have not. The more I think about it, the more I have the opinion that the rule can be simply removed without changing anything (because I do not believe that you can implement deliberate obstruction using a wide stance without massively shooting yourself in the foot).
