### ISSUE TITLE
Visual Referee Challenge: Delay until signal is shown

### ISSUE THREAD

**Issue by roefer** [RoboCup-SPL/Rules#119]
The rules say:

> At the T-junction of the center field line a challenge assistant will show within 5 s after the whistle a random hand-signal and direction according to the list below for 10 s.

"Within" probably means that this can also be less than 5 s. As a result, the signal "Player exchange" could basically start immediately after the whistle. However, the first phase of that signal is probably only shown for 3 seconds (three slow rotations). So it might be over before the robots have the chance to look at the referee.

It might be a good idea to specify a minimum delay before the signal starts or increase the number of rotations.

**Comment by PatrickGoettsch** [comment]
We are going to introduce an initial delay of 5 seconds.
