### ISSUE TITLE
In-game Visual Referee Challenge: Hand signal lists

### ISSUE THREAD

**Issue by roefer** [RoboCup-SPL/Rules#120]
The challenge rules for the in-game visual referee challenge state:

> The challenge assistant has to select before the match starts a suitable number of hand-signal and direction pairs and note them down. 

This seems to be quite impractical. I am sure that the TC wants to have the signals picked in digital form to compare them with the logs of the game controller. In addition, challenge assistants might underestimate the number of signals they will actually need.

I would suggest that the TC prepares random lists of signals that fulfill the requirements of the challenge in digital form and also print them. Challenge assistants can then request such a list shortly before the start of the game. These lists should contain a sequence of around 25 hand signals each.

There is also a problem with:

> Any whistle within 30 s after another whistle has to be ignored.

If signals are not shown if less than 30 s have passed, there might occur a problem with the synchronization between the time measured by the challenge assistant and by the GameController (which measures the time between button presses, not whistles). If the two sequences are not synchronized anymore, the teams might loose a lot of points because the wrong signals are compared with each other when the challenge results are computed. So I would suggest to progress in the list with each whistle, independent of whether enough time has passed. The signal should also be shown if less than 30 s have passed to avoid that no signal was shown when the GameController measured slightly more than 30 s. This would lower the average score of the teams.

**Comment by PatrickGoettsch** [comment]
We agreed on generating many lists, which are handed over to the referees before the game. This list contains a numerous referee signs.
Regarding the point of evaluating the challenge. The referee is going to show a sign at each whistle. We will look into how this works during the competition.
