### ISSUE TITLE
Shared Autonomy Challenge

### ISSUE THREAD

**Issue by roefer** [RoboCup-SPL/Rules#139]
Here a few thoughts about the challenge:

  - The rules should define a reasonable upper limit for the network bandwidth that can be used. It is true that no bandwidth can be guaranteed, but it would be unfair if none is available because the opponent is using up the whole bandwidth.
  - The scoring in the challenge highly depends on the opponents a team has to play against. So if different teams played against different opponents, their direct results might not be comparable. It might be better to use some variation of the Swiss system in the challenge to determine a ranking.
  - If a team finds a genius but simple to implement method to integrate the human operator into the game, it puts that team at a disadvantage if it has to tell the other teams about their method before the challenge starts.

**Comment by jpha226** [comment]
Thanks for sharing these. We discussed this point and will look into a possible way to determine fair use of what bandwidth is available. We are hesitant to limit the different approaches teams might take as to what information is streamed back to the human operator. However, we will make sure to note that attempts to jam the other team should not be taken. There was also a suggestion that we could attempt to configure the network router to try and balance how much each team can get through.

Thanks for the suggestion for a variation on the Swiss system. It's a great idea to get a better selection of matches and we'll try to find something that works as we know how many matches can be played.

The point of disclosure is to make sure that teams provide a minimal level of human control, i.e., all challenge participants do more than just deploy two fully autonomous robots. We are discussing delaying when teams must communicate their strategy to mitigate the risk of other teams quickly copying their approach. One possibility is that teams will disclose to the TC initially but then later to everyone else.

**Comment by ahasselbring** [comment]
Can the operator-robot communication use a different network channel than the one for team messages (i.e. non-UDP, different port, and/or unicast)? Otherwise, the GameController will count those packets as team communication, which prohibits packets larger than 128 Bytes. I would guess from the above reply that you allow any (reasonable) network channel for operator-robot communication, but as this is one of the topics where the normal rule book is quite strict, a clarification would be good.

**Comment by jpha226** [comment]
Yes, any (reasonable) network channel is fine for operator-robot communication. Robot-robot communication will still be restricted as per the normal rules.
