### ISSUE TITLE
Standard Removal Penalty

### ISSUE THREAD

**Issue by roefer** [RoboCup-SPL/Rules#140]
The section about the Standard Removal Penalty ends with this sentence:

> Once the penalty time has run out, the operator of the GameController will send the playing signal to it.

What is "it"? Probably the penalized robot, but that one was last mentioned three paragraphs before. And technically, there is no "playing" signal. The robot's penalty is simply set to "none".

In addition, it would be nice to mention that all this means that robots are unpenalized where they stand, i.e. 50 cm away from the touch line and maybe not on the height of the penalty mark.

**Comment by arnemoos** [comment]
Good hints, we will formulate this more clearly.
