### ISSUE TITLE
Shared Autonomy Challenge Questions

### ISSUE THREAD

**Issue by philipniklas-r** [RoboCup-SPL/Rules#142]
I got a few questions to the challenge:

> - 2.2.1: Each participating team will set up one fully autonomous robot ...

As the normal SPL rules still apply (``If not otherwise stated, the Champions Cup rules will be in effect.``), the robots are still allowed to communicate with each other. This means it would be allowed to send information from the human controlled robot to the autonomous robot. For example to communicate to the autonomous robot to position itself at a specific field point for a pass. But this could also be abused to also kind of control the autonomous one with just the wireless communication packages. Therefor is everything allowed to be communicated (based on the normal communication rules) between the robots, or should this be adjusted for the spirit of the challenge?

> - 2.2.4 : The defending team is not permitted to score

If the defending team scores a goal, what will happen? Is it just a goal kick for the attacker team, or is the robot of the defending team penalized as a result?

>  - 2.2.4  Matches end in wins, losses, or draws depending on games scored.

The defender team is not allowed to score goals. This means the defending team can only get points with passes. Does that mean a win or loss per game is decided based on the number of goals, but in case of a 0:0 (the attacker team did not score a goal) the defender team wins if it did more passes? Or can the defender team always win as long as it scored more points, even if the attacker team scored a goal?

**Comment by jpha226** [comment]
Thanks for the questions. For the first concern, it's a good point but it can be hard to draw a clear line between when communication crosses the boundary between coordination and direct control. We will clarify the spirit of the challenge in the rules but decided to err on the side of less restrictions on what can be communicated so as not to inadvertently discourage interesting ways of coordinating the robots.

If the defending team scores a goal then a goal kick will be awarded to the attacking team. Effectively, we will treat the entire end line of the attacking team's side of the field as an out of bounds line.

Matches will be decided based on points. So hypothetically, if the initial defending team gets the ball and successfully passes back and forth a sufficient number of times and then the attacking team scores and then no points are scored when the defending team becomes the attacking team, then the initial defending team wins the match.
