### ISSUE TITLE
Team messages must be counted during Initial

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#151]
Someone noticed an interesting consequence of the GameController's design that any action that couldn't happen during a delayed state will end the delay: https://github.com/RoboCup-SPL/GameController3/issues/54

I think that given the current rules, the GameController is actually right (otherwise you could derive the true state from a decreasing message counter) and the problem is that team messages are not counted during Initial. Now that there are things going on during Initial that could make sending team messages useful, messages should be counted during all states (I'm not sure whether Finished should still be excluded).

**Comment by sseering** [comment]
We discussed this in the last TC meeting: for this year we don't want to change the implementation of the rules or GC in this regard. We are accepting that team may send lots of messages during the Inital GameState without being counted towards the message budget.

The TC might revisit this for 2025.

**Comment by ahasselbring** [comment]
By the way, as a workaround, the current GameController implementation does not count team messages during the first 30 seconds of the first Ready state.

For the future, the relevant state is Standby.
