### ISSUE TITLE
Clarify how to get a robot from unstiff to initial

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#2]
In game_process.tex:

line 27:
> Pressing the chest button once while in the \textit{unstiffen} state, permits the robot to \textit{stiffen} it’s joints and return to the initial state, or a state as indicated by GameController.

line 61:
> Pressing all \textbf{three head buttons} in the \textit{unstiff} state allows a transition to the initial state, or a state as indicated by the GameController.

Personally, I would prefer the first option (i.e. the chest button).

**Comment by PatrickGoettsch** [comment]
Adresses in 5b3ed25
