### ISSUE TITLE
GC connection 

### ISSUE THREAD

**Issue by PatrickGoettsch** [RoboCup-SPL/Rules#24]
After gore: new rule: a robot of a remote team does not listen to the GC then it is ejected from the game

**Comment by ahasselbring** [comment]
What exactly is the difference to non-remote teams' robots? That they can't pick up the robot, change the software, and let it reenter?

**Comment by rvilling** [comment]
Why should the rules differ for a remote team in this case? Is the challenge and responsibility not identical for local and remote teams?

As a minor detail, how will you decide if a robot does not listen to the GC as opposed to that it does listen but has some other bug in a particular state? If this is something that only applies in the ready state or on return from penalty (e.g. after request for pickup) then it makes a bit more sense to me.

**Comment by PatrickGoettsch** [comment]
Does not apply to RC2022
