### ISSUE TITLE
Penalty Kick during Free Kicks?

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#25]
At GORE, a penalty kick was awarded while a goal kick was active: https://youtu.be/0HfVJuWJvO8?t=33633

The GameController currently does not allow this due to my understanding of
> Additional penalties against any further robots during the free kick, including Pushing, do not result in an additional Free Kick, but still use the appropriate removal penalty.

in section 3.7. Is this correct?

**Comment by PatrickGoettsch** [comment]
#33 will answer the question

**Comment by PatrickGoettsch** [comment]
Is postponed to next year's discussion

**Comment by PatrickGoettsch** [comment]
Should be kept simple. No
