### ISSUE TITLE
Decision of play-off games when both teams exceeded their message budget

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#26]
What happens if both teams exceed their message budget in a game that requires a winner? Is there a penalty shoot-out in which goals count as usual? Immediate coin toss?

(And what if there is a 0:0, but only one team exceeded its budget? Is the penalty shoot-out played and the team that can't score can still win via coin flip if the other team doesn't manage to shoot/score at all?)

**Comment by PatrickGoettsch** [comment]
Addressed by #34
