### ISSUE TITLE
3.3.1 invalid goal

### ISSUE THREAD

**Issue by rvilling** [RoboCup-SPL/Rules#37]
The text reads "A goal is invalid (that is, it can never be awarded) in the following circumstances: 1. When an Indirect Kick has not occurred (see Section 3.3.2)." This statement seems misleading as it implies that all goals must be indirect. Better to slightly reword as "1. When an Indirect Kick is required has not occurred (see Section 3.3.2)."

**Comment by PatrickGoettsch** [comment]
Please have a look into PR #31

**Comment by rvilling** [comment]
PR #31 doesn't help. This is a problem of wording in section 3.3.1.

**Comment by PatrickGoettsch** [comment]
Got updated now
