### ISSUE TITLE
3.3.4 Initial kick-off

### ISSUE THREAD

**Issue by rvilling** [RoboCup-SPL/Rules#38]
In the first paragraph of 3.3.4, "Robots **have to be handed over** at latest 2 min before an initial kick-off. [...] placed on the sidelines [...] by the referees. Robots are brought into the initial state after they are placed."

In the second paragraph: "A team may choose to place their robots themselves for initial kick-off, if they are present in person
at the competition site" and "All robots are brought into the initial state by their team or referee at latest 1 min before ready gets called".

There seem to be 2 inconsistencies here:
1. It cannot be that teams have to hand over robots, but can choose to place robots themselves. If the second choice is desired then the language in paragraph 1 needs to be changed.
2. There also seems to be a slight inconsistency for when robots are brought into the initial state. In paragraph 1 it seems that robots would be standing around in initial for around 2 mins whereas in paragraph 2 robots only need to be standing in initial for 1 min.

**Comment by PatrickGoettsch** [comment]
#54 should solves this
