### ISSUE TITLE
Initial kick-off

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#4]
From what I understand, section 3.4 has been changed so that the robots aren't placed by the playing teams at arbitrary positions anymore, but are instead handed in before a half / after a timeout (I guess so, at least it would be strange if the kick-off after a timeout follows a different procedure than before a half) and placed at standardized spots by the (assistant) referees.

This leaves some open questions:
- The rules specify that the robots are handed in in the unstiff state and later receive the ready signal from the GameController. I think that the referees must transition the robots into the initial state in between (by doing whatever the outcome of #2 is).
- The rules don't specify a timeframe for the procedure. Given that 2-3 referees have to place 10 (or even 14) robots, there should be a clear deadline by which robots must be handed in.
- The rules could be more specific on the position and especially orientation of the setup, i.e. are the robots positioned with their feet's center on the touchline or completely behind the line (the standard removal penalty rules aren't more specific than "on the sideline" although Figure 9 looks as if they were placed behind the line)? Are the robots oriented orthogonal to the touchlines?

**Comment by PatrickGoettsch** [comment]
We inserted an opening that onsite teams can place their robots on their own.
Unstiff to initial transition is now handled
Period for handing in is given. The robot's orientation is now specified. But the exact position is left open and brings in some random factor teams must deal with.

Addressed in d5094659e3adf01e1520a3d07a92e077456436a5
