### ISSUE TITLE
Dynamic ball handling over-restrictive definition of a valid pass

### ISSUE THREAD

**Issue by rvilling** [RoboCup-SPL/Rules#59]
The current text for the dynamic ball handling challenge indicates that "A pass counts as a valid pass if the ball stops in front of
the receiving robot towards the opponent’s goal". 

The rule as written explicitly prevents a pass to the feet of the receiving robot if the receiving robot is further forward than the passing robot. In this situation it is quite typical in real soccer that the receiver of the pass is turned (at least partially) to face the passer and if the ball stops at their feet then the ball is not "in front of the receiving robot _towards the opponent’s goal_". This restriction doesn't seem appropriate.

I suggest removing at least the text that says "towards the opponent's goal" and I wonder if the requirement that it should be in front of the robot is also too restrictive. For example, should a pass that is just to the side of the robot be excluded?

**Comment by PatrickGoettsch** [comment]
Hi @rvilling please have a look into #58

**Comment by PatrickGoettsch** [comment]
And there is this half circle around the robot where the ball is allowed to arrive towards its next target. This rule should only prevent that the pass causes the receiver to walk backwards to play the ball.

**Comment by rvilling** [comment]
I think in real soccer the attacking players on the centre line would often have an open pose (see attached diagram) to receive the ball to their feet and then once they have the ball turn to play it forward. Is there any reason why we should prevent this? In this case, I suggest the semi-circle is in front of the robot and not locked to the direction of goal. 

Otherwise the challenge mainly focuses on who can calibrate a kick to always land between 0 and 100 cm ahead of the target robot without touching the target robot. This is OK in some situations but is not appropriate for all passes.

<img width="421" alt="Screenshot 2022-05-12 203432" src="https://user-images.githubusercontent.com/3924498/168155269-f29abcad-04f6-46f1-8fc3-d6650048775b.png">

**Comment by PatrickGoettsch** [comment]
Rudi, I do not get your point. In the mentioned PR it got phrased like you suggested I think.

> A pass counts as a valid pass if the ball stops in front of the receiving robot towards the next target either 2nd receiver or opponent's goal. The receiving robot should not have to move backwards, to play the ball. When the ball stops, it has to be in the vicinity of the receiving robot (at max approx. \qty{1}{\metre} distance between receiver and ball, see~\cref{fig:ball_handling_positions}).
