### ISSUE TITLE
Do we keep the future-changes section?

### ISSUE THREAD

**Issue by sseering** [RoboCup-SPL/Rules#6]
I noticed content/app_future_changes.txt is ignored by the LaTeX build but still present in the Repo. It even referenced from the other text (and caused a broken link in the current Rules PDF).

With f73b63e33291be09db1e9598a4149ecb6287ae5d I added it back into the rules. I did this to make sure we don't loose anything if we choose to do nothing from now on as the fallback case.

Do we want to keep this section? Is it still relevant? Was it supposed to be deleted? Was it just lost during the split from 1 file into several? (Where is the table from Rudi?)

**Comment by PatrickGoettsch** [comment]
Have been removed
