### ISSUE TITLE
Dynamic ball handling request for clarifications

### ISSUE THREAD

**Issue by rvilling** [RoboCup-SPL/Rules#61]
In the dynamic ball handling challenge:

1. Can the attacking robots dribble/move the ball to a better position before kicking to pass? (Otherwise it seems a well positioned defender could block the angle from the current ball position and the attackers could do nothing then.)
2. When the final attacker receives the pass, is the only option available to take a shot immediately from where the ball lands or can they dribble or reposition the ball for a better angle? Could they even decide to pass back to their teammate again?
3. The attacker starting positions are defined. Once the challenge starts are attacking robots free to reposition themselves to get better angles? If they can move, are there any restrictions on this movement?

**Comment by PatrickGoettsch** [comment]
You comments and questions have been addressed in the recent version of the PR #58
