### ISSUE TITLE
Visual referee challenge - clarification of directions

### ISSUE THREAD

**Issue by rvilling** [RoboCup-SPL/Rules#62]
In section B.2.2 the text says

> The description of this challenge (and hand-signals) is described based on the viewpoint of the
> head referee. In these descriptions the “red team” is defined as playing from left-to-right, and the
> “blue team” as playing from right-to-left.

Can I assume that the just defined red and blue team directions are from the viewpoint of the referee then (since otherwise these would not traditionally be the directions for the red and blue team when starting a game). If my assumption is true, can we rephrase the second sentence slightly to avoid doubt:

> The description of this challenge (and hand-signals) is described based on the viewpoint of the
> head referee. In these descriptions the “red team” is defined as playing from _the referee's_ left-to-right, and the
> “blue team” as playing from _the referee's_ right-to-left.

**Comment by ahasselbring** [comment]
B-Human is also a bit confused about this at the moment - our implementation was already changed a few times over different interpretations of the rules.

**Comment by rvilling** [comment]
For Figure 16 (Pushing free kick), there is some ambiguity about the call and the arm direction.

The wording "given the penalty" is a little ambiguous. It would be better to say "penalized" if that is the intended meaning.

If I am correct to interpret "given the penalty" to mean penalized, it seems that the direction of the extended arm for pushing free kick is different to all the previous calls. For kick-in, corner-kick, and goal-kick, the extended arm points to the team that is _awarded_ the kick (i.e. takes the set play kick). For pushing free kick the extended arm points to the team committing the foul. Is this the correct interpretation?

For the the audio "pushing free kick [colour] team", is the colour also the team that committed the foul?

**Comment by PatrickGoettsch** [comment]
B2.2 should be now much clearer. I added also a picture

**Comment by timothy-wiley** [comment]
Hi, With the large volume of alerts from Git, I have not seen these until Rudi kindly brought these to my attention.

> Can I assume that the just defined red and blue team directions are from the viewpoint of the referee then (since otherwise these would not traditionally be the directions for the red and blue team when starting a game). 

Yes. Feel free to rephrase if you think it's clearer. So long as it's consistent I don't have a preference. The observation is that to try and phrase terms similar-ish to current calls, which use team colours not ref facing directions. Given there is no team, I chose to revert to the "traditional" red/blue.

>The wording "given the penalty" is a little ambiguous. It would be better to say "penalized" if that is the intended meaning.
>If I am correct to interpret "given the penalty" to mean penalized, it seems that the direction of the extended arm for pushing free kick is different to all the previous calls. For kick-in, corner-kick, and goal-kick, the extended arm points to the team that is awarded the kick (i.e. takes the set play kick). For pushing free kick the extended arm points to the team committing the foul. Is this the correct interpretation?

This may be my parlance from Australian ball-sports that could differ from international human soccer.
My phrasing should be

- The "penalised" team committed the foul
- The team that "received the penalty" is the _other_ team that should get possession of the ball. Ie that have "received the benefit of the penalty". 

However, please rephrase to be consistent (or clarity) with human soccer parlance.

**Comment by timothy-wiley** [comment]
Further, if the images need changing I can add a photoshop version of the file if others wish to modify them.

**Comment by PatrickGoettsch** [comment]
@timothy-wiley  could you review my suggested changes in #63
