### ISSUE TITLE
Extend Goalkeeper Privileges to the Penalty Area

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#66]
The goalkeeper has some special privileges that field players don't have (not mentioning its special role during penalty kicks here):
1. playing the ball with arms/hands (in its own goal area)
2. diving to intercept the ball (in its own goal area)
3. holding the ball for up to 10s (in its own penalty area) instead of 3s
4. pushing other players while looking at or chasing the ball (in its own goal area)

(1), (2) and (4) were adjusted to the goal area in 2022 to keep the same meaning as before the 2020 growth of the penalty area (I think (3) was just forgotten). However, I would argue that extending these privileges to the penalty area (at least for (1) and (2)) this would be aligned with real soccer rules) encourages a more active (and realistic) goalkeeper gameplay, as compared to the current situation in which goalkeepers are mostly confined to the 2.2m by 0.6m goal area.

I'm not too sure about (4) in general since this rule basically means that the decision whether the goalkeeper is "looking at or chasing the ball" decides whether nothing happens at all or there is a penalty kick for the opponent against an empty goal, but this may be a separate discussion (in general, the most controversial decisions can have the largest impact, but this is sometimes the case in real soccer, too).

**Comment by rvilling** [comment]
The proposal to extend (1) and (2) to the penalty area seems reasonable

**Comment by PatrickGoettsch** [comment]
Than I would add 4 as well

**Comment by ahasselbring** [comment]
(4) has been included, too.
