### ISSUE TITLE
Rules/Statements to Remove

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#68]
This is a collection of rules and statements that can/should be removed from the rule book in my opinion. I will continue to extend this list.

- 1.3 "Lighting Conditions": The 10:1 ratio is useless without specification how it is measured (e.g. log-scale for perceptual ratio?) and how it is enforced (e.g. using the lux scale, sunlight will usually be much more than 10 times lighter than shadow, which is something that we actually want). The second paragraph could be removed entirely because "old" teams should know by now that lighting can change, and new teams have no reason to expect anything else.
- 1.7 "Streaming setup": What is the purpose of this section? In its current state, I would remove it entirely. If it contained some description on how the setup actually works, it would be better suited for an appendix.
- 2.1 "Hardware": Remove the paragraph about the GameController/TCM computer. This chapter is called "Robot Players" and this has nothing to do with it.
- 2.2 "Goalkeeper": Currently, this lists only "playing with arms/hands" as a special privilege of the goalkeeper. I think this should be replaced by a statement that says that the goalkeeper has *some* special privileges, because it otherwise creates the wrong impression of being a complete enumeration.
- 2.4 "Team Markers": The submission/approval of jersey designs should be a competition rule.
- 2.4 "Team Markers": There is still a sentence about "Attaching player numbers to the heads and/or legs of the robots.". I think nobody does this anymore (NOTE: This is *not* the same as putting the robot name / owning team on the body, which is allowed in a separate point, although only on the torso)
- 4.3.2 "Locomotion Type": I don't think this rule is useful in any way.

Added on 13.12.:
- 4.3.3 "Damage to the Field": Tim L. proposed to remove this because "A NAO that poses a danger is certainly not able to play the game to its end." Since walking into the goal posts or the goal net is leaving the field, it is actually quite unclear to me what a robot would have to do for a referee to call this penalty, and a rule of which referees don't know when to apply it isn't much use.

Added on 17.12.:
- 1.2 "Field Colors": The color of the goals is already given in figure 3. The color of the field is currently not mentioned in 1.1 but can easily be added, and the color of the lines is already given there, too. Therefore, by adding "green" before "artificial turf" in the first sentence of 1.1, this entire section becomes redundant.

**Comment by rvilling** [comment]
1.7 - some brief mention of streaming could be included in venue setup (1.4), along with the need for tables for the GC along one side of the field since this does actually affect the venue setup. Stricty section 1.4 is currently a bit of venue setup and then mostly field dimensions/field construction. Not sure if that section should be named differently or not.

2.1 - again this aspect of GC hardware could potentially be moved back to venue setup. At the moment this information is not visible to LOCs each year until they are contacted by the SPL OC.

2.2 fine

2.4. submission rule - I suggest just saying that jersey designs are subject to approval by the TC 2 months before the competition.

4.3.2 agree

**Comment by PatrickGoettsch** [comment]
1.3 remove, because we can only ask for this but cannot enforce it.
1.7 Would keep this like Rudi said
2.1 as Rudi said
2.2 agreed
2.4 There is already some deadline for this in the rules.
4.3.2 agree
4.3.3 agree
1.2 makes it easier.

**Comment by ahasselbring** [comment]
#102 is related to 1.7/2.1.

**Comment by ahasselbring** [comment]
Most of this has been done.
