### ISSUE TITLE
More Flexible End of Half

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#69]
At the moment, referees often try to whistle at the end of a half exactly when the GameController counts down to 0, regardless of what is happening on the pitch. Sometimes, referees end a half early if a goal has just been scored and it is clear that the remaining time is not sufficient to score a goal (especially in preliminary games), which is usually good. On the other hand, referees (almost?) never extend a half (except for technical reasons such as the GameController being started in preliminary mode for an actual play-off game), even if a ball is rolling towards a goal. It must also be noted that the GameController time may not even be precise to the second, due to delays in the operation of the program (e.g. the playing button is pressed after the initial whistle), so it is not an unbiased source either, and the decision whether a goal still counts or not is quite arbitrary.

I propose the following two conditions for ending a half:

1. The half is finished only once the ball has stopped moving or is deliberately played (similar to other rules, simple deflections would not end the game and a goal could still be scored). That is, if the ball is already stationary when the clock reaches 0, the half still ends immediately.
2. Similarly, penalty kicks that have been awarded before the end of the regular time should be continued to be executed (even if they are still in the ready/set state). As soon as the ball is played a second time after the penalty kick (or a goal is scored or the ball comes to a stop or is clearly deflected away from the goal), the half is over.

**Comment by PatrickGoettsch** [comment]
Good point. It is handled differently in different sports. But we should for my opinion go in the direction of you proposed version.

**Comment by ahasselbring** [comment]
One argument here was that this disadvantages dribbling teams.

**Comment by ahasselbring** [comment]
After thinking more about it, I don't consider the "dribbling team" argument to be valid. It went about:
- Suppose it is 1 seconds before the time runs out and a player is lined up behind the ball 4m away from the goal.
- Dribbling from here will definitely not score a goal. Shooting (with the current rules) probably neither because the ball cannot reach the goal in time.
- After the rule change, shooting in this situation can be successful, while dribbling (i.e. making a weak movement towards the goal) will still not score in time.

In summary, yes, this rule change creates situations in which one action is better than the other. So what?

The argument assumes there is a right for teams that an inflexible strategy must not be at disadvantage compared to a more flexible strategy (consider a strategy that is derived from the "dribbling strategy" by adding a "rule" that x seconds before time runs out a shot is attempted instead of dribbling further - since the remaining time is sent by the GameController, this isn't a large challenge). Real soccer players that can only dribble are also at a disadvantage, and you wouldn't blame the rule book for it.

The argument "if a team is really better, it would have had 10 minutes to score, so why should it need a few fractions of a second at the end of a game?" still stands and I consider it more valid than the "dribbling team" argument, but not really convincing in this case.

**Comment by PatrickGoettsch** [comment]
[Minor] Don’t finish games at least until the ball comes to a full stop (or e.g. a penalty kick is executed). GameController time gives a false sense of precision and a few more seconds don’t break the schedule. (Arne Hasselbring, B-Human) 13pro

Was what we had discuss in Bangkok

**Comment by PatrickGoettsch** [comment]
I would phrase it like this: The game is over after 10 minutes the ball comes to full stop after the last kick of a robot and the game phase is playing. If it gets kicked again after the 10 minutes counted down, the half ends, too (So no option to keep it rolling but allow deflections). If the ball stops inside the goal, it gets awarded according to the general rules (no own goal at kick-offf)
