### ISSUE TITLE
Code Releases

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#70]
At RoboCup, a majority of teams voted for the proposal of "Mandatory full (i.e. the source code that has played in the last game) code releases immediately after RoboCup for all teams". This can be split into the following three sub-points:

1. Instead of code releases being a requirement only for pre-qualification for the next competition, they could be "attached" as a (post-)requirement to the same competition. Instead, a qualification penalty would be given for not publishing the code release in time (this would automatically remove any pre-qualified status). This would 
  - eliminate a theoretical loophole by which a quarterfinalist submits a regular application (instead of using pre-qualification) to avoid releasing code
  - make new code releases available earlier in the season
2. Require code releases from all teams (and not just the quarter finalists).
3. Require "full" code releases. It would be to defined what "full" means, but I think it would have to be possible to compile the code etc. to fully recreate a state that played at RoboCup.

**Comment by ahasselbring** [comment]
As far as I understood it in the meeting we just had:
We are in favor of (1) and (2), but against (3). Still, the released code must be related to the own contributions that are actually used during RoboCup.

**Comment by PatrickGoettsch** [comment]
- [ ] Qualification penalty
- [ ]  Publish by 15th of October ...
