### ISSUE TITLE
Team Contribution Poster (A.1)

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#72]
In 2022, the requirement for the team contribution poster was waived about one month before the competition.
For 2023, I would like to have the rule book be consistent with reality, so we should decide early whether the poster requirement is kept or removed (and then stick to the decision).

In some sense, the TDPs should replace the need for the poster as something that every team has to do to show others their contribution, but they are still at different points in time (i.e. the TDP says what is expected to be done, while the poster at RoboCup can tell what actually has been done). The SSL for example requires both (E)TDPs and A0 posters from division A teams.

**Comment by PatrickGoettsch** [comment]
And it is not only for the other teams. It should also be for the audience.

**Comment by PatrickGoettsch** [comment]
Mention this in some newsletter

**Comment by rvilling** [comment]
What did we decide to do about TDPs for the SPL?

**Comment by PatrickGoettsch** [comment]
Yes, as written in the CfP: https://spl.robocup.org/call-for-applications-for-participation-2023/

**Comment by PatrickGoettsch** [comment]
Got announced
