### ISSUE TITLE
Visual Referee Challenge 2.0

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#73]

**Comment by PatrickGoettsch** [comment]
> Have less Technical Challenges. At RoboCup 2022, there are four challenges but only few participants in each. Many teams do not have the manpower to implement solutions for all challenges. Having, for instance, only two challenges and a stronger incentive for participation would lead to more interesting overall results, I guess. (Tim Laue, B-Human) 13pro

I would go for a ingame challenge, see #80

**Comment by PatrickGoettsch** [comment]
Replaced by #79
