### ISSUE TITLE
Dynamic Ball Handling Challenge 2.0

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#74]

**Comment by arnemoos** [comment]
Proposed changes to the 2022 DBHC rules: 

- [ ] easier positioning, attacker inside the one half and defender in the other (sideconfidence & localization should not be challenged) 
- [ ] randomness in x- and y-direction for all objects (robots and ball)
- [ ] ball is not allowed to be placed on the penalty mark for additional feature on the field
- [ ] three single runs with time for fixes in between 
- [ ] for each run teams should play against the same defending image (if possible) and nearly the same randomness to make these runs comparable
- [ ] different/optimized scoring (failed runs should also be distinguishable and not only 240s)  

- [ ] should meta gaming of the defenders be prevented (walk towards the robot which probably gets the pass instead to the one which actually has the ball)?

**Comment by PatrickGoettsch** [comment]
Publication of code

**Comment by arnemoos** [comment]
Pull Request #95 
- [ ] Final score should be the mean of points or the median? 
- [ ] Remove/Rephrase wording regarding "old" defender images
