### ISSUE TITLE
Data Minimization Challenge (in-game)

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#75]

**Comment by EmanueleMusumeci** [comment]
Thanks for opening this issue! I recall this is the only in-game sub-competition we have agreed to, up until now, am I right?

**Comment by PatrickGoettsch** [comment]
So far you are right. But maybe there are ideas for more. Let us see.

**Comment by EmanueleMusumeci** [comment]
We have so far decided that we want a different winner for each sub-competition (one for CC and one for CS) and that the challenge should not take only into account the quantity of exchanged bytes but also the performance linked to that data exchange ("quality").

The most important things to discuss are:

1. Do we want to make the rules actually the same for CC and CS or do we want to make rules more difficult for CC?
2. What is the best scoring metric to take into account both number of exchanged bytes AND quality of exchanged data (or performance of the team that might be related to network data usage)?

I will post a follow up in the next days with some ideas on the scoring metric.

**Comment by EmanueleMusumeci** [comment]
After giving good thought to this issue, I don't think we should include the number of goals in the scoring metric for the Data Minimization Challenge, as the number of scored goals goes beyond the purpose of this challenge. 

My proposal for a scoring metric is to keep track of the average number of exchange bytes-per-robot. In particular, given the possibility of keeping track of the number of bytes sent by each team number, the metric might be as simple as measuring the average bytes-per-robot $A_{bpr}$:

$$ A_{bpr} = \frac{1}{n} \left( \sum_{i=1}^n \frac{b_i}{t_i} \right) $$

where:

- $b_i$ is the number of bytes exchanged by robot $i$
- $t_i$ is the uptime of robot $i$
- $n$ is the maximum number of robots active in the team (therefore if, for example, a team decides to play in the 7vs7 competition with 6 robots, the metric will actually cover the performance of that formation with $n=6$) _**OR**_ the number of robots-per-team in the competition, 5 in 5vs5, 7 in 7vs7)

We might want to penalize bytes exchanged in specific game phases: for example, bytes exchanged when they're not expected like in ready phase or in set phase. In this case, the score would be the weighted sum of several averages $A^{\text{phase}}_{bpr}$, each one computed for each phase, each phase average weighted with a penalizing factor (a coefficient between 1 and 2), as in:

$$ A_{bpr} = \sum_{p \in \text{P}} c_p A^p_{bpr} $$

where:

- $P$ is the set of game phases $P = \\{ready, set, playing, ...\\}$
- $c_p$ is a penalizing coefficient for that specific game phase (for example, we might penalize additional traffic in the ready phase by using a coefficient of $c_{\text{ready}} = 1.5$

In any case, the final objective of each team is to minimize the $A_{bpr}$ average.

**Comment by EmanueleMusumeci** [comment]
@ahasselbring According to your last commit, do you think it might be fitting to add a paragraph about this challenge in the "SPL-Challenges" file?

**Comment by ahasselbring** [comment]
After the pull request #86 there is the file `challenges/data_minimization_challenge.tex`.

**Comment by EmanueleMusumeci** [comment]
About the new challenge name... I'm proposing a simple "Network Usage Challenge"

**Comment by rvilling** [comment]
I suggest not overcomplicating the metrics. There is no need to apply different weights to different game phases - it is up to teams how they spend their communications budget. 

Is it easy to measure the uptime of robots? (In Game Controller?) Will this deal also with request-for-pickup and rebooted robots, substitute robots, etc.?

**Comment by ahasselbring** [comment]
I agree with Rudi that introducing weighting is overly complicated or even counterproductive - there is no reason the challenge rules themselves should prefer communication in some situations over others.

It is possible to obtain *some* measure of uptime from the GameController, e.g. summing the time for each player in which it was *not* penalized. Since substitutes and picked up robots are penalized, they would not count towards the denominator (but shouldn't count towards the numerator). I think the more important question is if this is *meaningful*.

I would not sum over the ratio per player, but instead sum the numerators (payload of each player) and denominator ("uptime" of each player) first and then divide them (i.e. payload of entire team over uptime of entire team), although I cannot give a good reason now beyond that it "feels simpler" (but there are probably implications). At least this wouldn't require to know anything about substitutions etc.

**Comment by EmanueleMusumeci** [comment]
My proposal about giving different weights to data exchanged during different game phases was an attempt to give a measure of quality of the network usage but in all honesty I now see your point and I agree it is actually not up to us to give "directives" about when to send packets.

During the last TC meeting we all agreed that we should also give a measure of quality of the network usage (in addition to only evaluating "quantity").

If we still all agree that this is necessary, to give an alternative measure of "quality" we could replace the uptime with the number of packets sent by each specific robot IP (therefore sum over detected IPs in place of robot numbers), although this would mean that we award more balanced communication strategies (more balanced packet size throughout the match and more balanced communication share among robots of the same team).

**Comment by ahasselbring** [comment]
I think the quality should rather refer to the resulting gameplay. Another simple solution would be to have some cutoff criterion below which teams aren't ranked in this challenge (e.g. reaching the quarter finals - either in CC or CS).

The only thing that doesn't feel right is that at RoboCup 2022, the challenge would have been won (tied) by the two teams that didn't score a single goal on their own.

**Comment by EmanueleMusumeci** [comment]
Although I agree performance should have a direct impact on the ranking, the downside of keeping track of goals in this score would be the risk for the challenge of being automatically won by the winner of the main sub-competition (CC or CS). 

The cutoff seems like a great idea: we might for example automatically exclude from the challenge any team that did not score at least one goal (without considering auto-goals of the opposing team).
