### ISSUE TITLE
Goalkeeper Colors

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#76]
At RoboCup 2022 it was suggested (and largely agreed upon) that the goalkeepers should be distinguishable by wearing a different jersey than field players, as it is the case in real soccer. The reason why this would be actually useful (and not just making things more complicated) is e.g. that attackers can see which of the defenders is the goalkeeper (and thus can legally dive), or defenders can recognize their own goalkeeper without having to communicate.

There are some open questions:
- Would it be legal for both goalkeepers to play in the same color? In real soccer, it is:
   > "If the two goalkeepers’ shirts are the same colour and neither has another shirt, the referee allows the match to be played"

  The advantage is that teams only need one additional jersey, but then calls for the goalkeeper would be ambiguous. Calling the goalkeeper with the color of the field player jerseys would be confusing.
- Would the goalkeeper be allowed to have a different player number than 1?

**Comment by arnemoos** [comment]
Was this already agreed on in the TC? 
If we want to make such a change it is now a good time since teams (at least some of them) will have to create new jerseys anyhow.

**Comment by PatrickGoettsch** [comment]
We should keep in mind that you than also need a replacement color for the Goalkeeper. You cannot use just the away color.

**Comment by PatrickGoettsch** [comment]
But if we change this. I like the idea. We should emphasize this at some point. Because teams must do something with their jerseys.

**Comment by PatrickGoettsch** [comment]
With this we can drop the requirement that the goolkeeper has to wear no 1.

**Comment by PatrickGoettsch** [comment]
solved by #79
