### ISSUE TITLE
7v7 Details (Substitution)

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#77]
Should the player number 8 (or higher) be available in 7v7 games?

Should all legal player numbers in 7v7 also be available in 5v5 games (unlikely to be actually used, but could simplify things)?

**Comment by arnemoos** [comment]
I would say that the number 8 should be available as substitution and I have no objection against allowing all teams to choose their possibly only 5 players from the numbers 1 to 8

**Comment by PatrickGoettsch** [comment]
The question would be if an opposing team would use this, and the game controller sends this number if it breaks something in their code. I would propose to make it a change for 2023 for CC and for 2024 for CS.

**Comment by PatrickGoettsch** [comment]
We also should make clear that in the future even higher number of team members would be allowed. So, the team's software should work with that higher player numbers in the future.

**Comment by sseering** [comment]
In 0bc90d6cf6a42cde1315ecd610b35dfbdfeb6be1 I removed the sentence 

> A match is played by two teams, each consisting of not more than \textbf{5} players.

from the section describing robot players. As part of this issue we need to add an more elaborate explanation on the number of robots players depending on CC and CS.

**Comment by ahasselbring** [comment]
My approach to this is to state that the maximum number of players per team can be set by the competition rules to be 5 or 7. Champions Cup and Challenge Shield should be introduced in appendix A.1 (or even an own appendix) and then specify this.
