### ISSUE TITLE
Number of custom data bytes in SPLStandardMessage reduced to 128

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#78]
This was already decided in the last TC meeting. At the moment, the structure of the `SPLStandardMessage` is not defined in the rules. Nevertheless, the change should already be included in the document released on January 15.

**Comment by PatrickGoettsch** [comment]
I agree with you. We should make this part of the rules. We could give a sample C++ definition as download on the webpage and reference to it.  And in the Wifi section we can define the custom data size.

**Comment by PatrickGoettsch** [comment]
What is about the GC?

**Comment by ahasselbring** [comment]
The header file has been updated and an item added to the list of changes.
