### ISSUE TITLE
Team markers - Remove 70% 

### ISSUE THREAD

**Issue by PatrickGoettsch** [RoboCup-SPL/Rules#79]
As discussed last year with UNSW we should drop this rule.

**Comment by PatrickGoettsch** [comment]
- [ ] Remove 70%
- [ ] Allow numbers from 1 to 20

**Comment by sseering** [comment]
reference: https://github.com/RoboCup-SPL/Rules/blob/master/content/robot_players.tex#L49

**Comment by sseering** [comment]
Dont keep colour for ref callouts.

**Comment by PatrickGoettsch** [comment]
I have thought about the color thing. Still a team should define for each jersey set a color. In human soccer games the statistics in TV also show this color. Makes all the changes easier.

**Comment by ahasselbring** [comment]
Closed by #92
