### ISSUE TITLE
Penalty Kick

### ISSUE THREAD

**Issue by ahasselbring** [RoboCup-SPL/Rules#8]
1. About the penalty kick during a game the rules say
> Additionally, only the goalkeeper robot from the defending team may be within the penalty area. The goalkeeper robot must also be touching the goal line.

and
> The defensive goalkeeper robot must always be in contact with the goal line, and must remain on its feet.

Consider the case where the goalkeeper was penalized some time before the penalty kick and is unpenalized shortly before set. In that case, it would be impossible for it to reach the goal line and it would get another illegal position penalty. I would suggest that only positions *within the own penalty area* that are not on the goal line are illegal, i.e. it is legal for a goalkeeper to stay out of the goal area for the duration of the penalty kick (until the attacker touched the ball and the penalty kick is over). Of course this is a very bad situation anyway, but at least the goalkeeper could avoid an additional penalty if it stays out of the penalty area once it is clear it cannot reach the goal line in time.

2. In the penalty shoot-out rules it says
> (This striker position is denoted by a small dot made with a felt-tip pen.)

This seems outdated because the position is now *on a field line* aligned with the penalty mark, so there should be no need for this.

3. Also in the penalty shoot-out:
> The goalkeeper robot must always be in contact with the goal line, is not permitted to leave the goal area, and must remain on its feet until the striker robot touches the ball. [...] Furthermore, the goalkeeper is not allowed to touch a ball that is completely outside the penalty area (the line is part of the penalty area).

Doesn't the first part ("always be in contact with the goal line") imply that it does not leave the goal area (at least if it's extended to "in contact with the goal line *between the goalposts*")? Also, touching a ball that is completely outside the penalty area seems physically impossible to me, especially given that the ball already starts within the penalty area.

4.
> The referees will use the button interface to switch the robot between playing and penalized.

There could be a clarification that the robot is also unpenalized after 15 seconds (if this doesn't seem obvious to everyone). Otherwise you would have an advantage by using the button interface in a penalty shoot-out since you wouldn't have to listen to the whistle. Maybe this is obsolete anyway as the software can't be changed between the end of the regular game and a penalty shoot-out?

5. Sudden Death
> If neither team score a goal, then a shot blocked by the goalkeeper beats a shot blocked by the goalpost which beats a wide shot. For example, if the shot of one team gets stopped by the goalkeeper and the other executes a wide shot, the first team wins. If both shots are wide, the shoot-out is repeated.

I remember that this was discussed in 2019, but aren't the cases "both shots stopped by goalkeeper" and "both shots blocked by a goalpost" unhandled? The last sentence then should be "both shots are in the same category" instead of "both shots are wide".

**Comment by PatrickGoettsch** [comment]
All points have been addressed in a60dccf
