### ISSUE TITLE
Remove indirect kick after kick-off

### ISSUE THREAD

**Issue by PatrickGoettsch** [RoboCup-SPL/Rules#83]
There is no indirect kick in the soccer rules at kick-off

**Comment by ahasselbring** [comment]
I support this change for consistency with real soccer. (I think on the topic itself and its implications, everything has already been said in discussions last year.)

On the other hand, if you really wanted to be consistent, you would also have to penalize the player taking the kick-off for touching the ball again before it has touched another player (and direct own goals could not be scored).

**Comment by PatrickGoettsch** [comment]
Good point. Is now in the PR
